# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7657c3aa3769e82d5fd376d5c25afffd629388833b9778907eb4ffbd7f03ae7857d2a2f46f17a0e6b965ed80b69f10ae5e1f34d3afafd23afbf4d22d2eff04d6

test:
  secret_key_base: 8dfec8ff3006ddf1770eec75ed2bf0303ade2d4ee0f5cf8c6a06c4e40e71495e4ed03f10a53997a544def4a9732bbd72bd7a2a6ed7664e245a449c3a286f0e31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
